server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: testswap-api
  datasource:
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Custom configs
testswap:
  rpc:
    url: ${TESTSWAP_RPC_URL:}
  fork:
    block: ${TESTSWAP_FORK_BLOCK:}
